name: voxel_to_mesh
channels:
  - conda-forge
  - pytorch
dependencies:
  # Core Python
  - python=3.9

  # Deep Learning (latest compatible versions)
  - pytorch
  - torchvision
  - pytorch-cuda=11.8

  # Essential packages only
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pyyaml
  - h5py
  - cython
  - setuptools
  - pip

  # Pip packages
  - pip:
      - trimesh
      - plyfile
      - tqdm
      - tensorboard
      - scikit-image
      - imageio
      - pillow
