name: voxel_to_mesh
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  # Core Python
  - python=3.9

  # Deep Learning
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.8

  # Scientific Computing
  - numpy=1.24.3
  - scipy=1.10.1
  - scikit-image=0.20.0

  # Data Processing
  - pandas=2.0.3
  - h5py=3.9.0
  - pyyaml=6.0

  # Visualization
  - matplotlib=3.7.1
  - imageio=2.31.1
  - pillow=9.5.0

  # 3D Processing
  - trimesh=3.22.4

  # Development Tools
  - cython=0.29.36
  - pytest=7.4.0
  - tqdm=4.65.0

  # Monitoring
  - tensorboard=2.13.0

  # Build Tools (Windows compatible)
  - setuptools=68.0.0
  - wheel=0.40.0
  - pip=23.1.2

  # Windows-specific (conditional)
  - vs2019_win-64 # [win]
  - cmake=3.26.4 # [win]

  # Pip packages
  - pip:
      - plyfile==0.7.4
      - pyembree==0.1.6 # For fast ray tracing
      - binvox-rw==1.0.1 # For reading .binvox files
      - open3d==0.17.0 # Alternative 3D processing
      - tensorboardX==2.6.1
