name: voxel2mesh
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.9
  
  # Core scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  
  # Image and mesh processing
  - scikit-image>=0.19.0
  - trimesh>=3.15.0
  
  # Visualization
  - matplotlib>=3.5.0
  
  # Utilities
  - tqdm>=4.64.0
  
  # Pip dependencies
  - pip
  - pip:
    - plyfile>=0.7.4
